version: '2'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    volumes:
     - ./docker/mariadb:/docker-entrypoint-initdb.d
    environment:
      - PS_FOLDER_ADMIN=admin087pqsbei
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
    networks:
      - prestashop

  prestashop:
    container_name: prestashop
    build: .
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./prestashop:/var/www/html
      - ./ssl:/etc/apache2/ssl:ro
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mariadb
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=https://localhost:8443
      - PS_FOLDER_ADMIN=admin087pqsbei
    networks:
      - prestashop

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    ports: 
      - 3306:3306 
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
networks:
    prestashop:

