version: '2'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    deploy:
      resources:
        limits:
          cpus: "0.875"
          memory: 1G
    volumes:
      - ./docker/mariadb:/docker-entrypoint-initdb.d
    environment:
      - PS_FOLDER_ADMIN=admin087pqsbei
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop
    networks:
      - prestashop

  prestashop:
    container_name: prestashop
    build: .
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 1G
    restart: unless-stopped
    depends_on:
      - mariadb
      - memcached-server
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./prestashop:/var/www/html
      - ./ssl:/etc/apache2/ssl:ro
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mariadb
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=prestashop
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=https://localhost:8443
      - PS_FOLDER_ADMIN=admin087pqsbei
      - MEMCACHED_HOST=memcached-server
      - MEMCACHED_PORT=11211
    networks:
      - prestashop

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512m
    links:
      - mariadb
    ports: 
      - 3306:3306 
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root

  memcached-server:
    container_name: memcached-server
    image: memcached
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 1G
    networks:
      - prestashop

networks:
    prestashop:

