{* Generated by Creative Elements, do not modify it *}
{ce_enqueue_miniature(6170101)}
<div data-elementor-type="product-miniature" data-elementor-id="6170101" class="elementor elementor-6170101{if !empty($productClasses)} {$productClasses}{/if}"><article class="elementor-section-wrap" data-id-product="{$product.id_product}" data-id-product-attribute="{$product.id_product_attribute}"><div class="elementor-element elementor-element-227e180 elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-section elementor-top-section" data-id="227e180" data-element_type="section"><div class="elementor-container elementor-column-gap-default"><div class="elementor-row"><div class="elementor-element elementor-element-218bb99 elementor-column elementor-col-100 elementor-top-column" data-id="218bb99" data-element_type="column"><div class="elementor-column-wrap elementor-element-populated"><div class="elementor-widget-wrap"><div class="elementor-element elementor-element-fb70091 ce-product-badges--stacked elementor-widget__width-initial elementor-widget elementor-widget-product-badges elementor-overflow-hidden" data-id="fb70091" data-element_type="widget" data-widget_type="product-badges.default"><div class="elementor-widget-container"><div class="ce-product-badges">
{if !empty($product.flags['discount'])}
<div class="ce-product-badge ce-product-badge-sale">
{$product.flags['discount'].label}
</div>
{/if}
{if !empty($product.flags['new'])}
<div class="ce-product-badge ce-product-badge-new">
{$product.flags['new'].label}
</div>
{/if}
{if !empty($product.flags['pack'])}
<div class="ce-product-badge ce-product-badge-pack">
{$product.flags['pack'].label}
</div>
{/if}
{if !empty($product.flags['out_of_stock'])}
<div class="ce-product-badge ce-product-badge-out">
{$product.flags['out_of_stock'].label}
</div>
{/if}
{if !empty($product.flags['online-only'])}
<div class="ce-product-badge ce-product-badge-online">
{$product.flags['online-only'].label}
</div>
{/if}
</div></div></div><div class="elementor-element elementor-element-fbaf5d5 elementor-widget elementor-widget-product-miniature-image elementor-widget-image" data-id="fbaf5d5" data-element_type="widget" data-widget_type="product-miniature-image.default"><div class="elementor-widget-container">{if $product.cover}{$image = $product.cover}{else}{$image = call_user_func("CE\Helper::getNoImage")}{/if}
{$caption = ""}
{$image_by_size = $image.bySize['home_default']}
{$ratio = round($image_by_size.width / $image_by_size.height, 3)}
{$srcset = ["{$image_by_size.url} {$image_by_size.width}w"]}
{foreach $image.bySize as $size => $img}
{if 'home_default' !== $size && round($img.width / $img.height, 3) === $ratio}
{$srcset[] = "{$img.url} {$img.width}w"}
{/if}
{/foreach}
<div class="ce-product-image elementor-image">
{if $caption}
<figure class="ce-caption">
{/if}
<a href="{$product.url}"><img src="{$image_by_size.url}" srcset="{implode(', ', $srcset)}" alt="{$image.legend}" loading="lazy"
width="{$image_by_size.width}" height="{$image_by_size.height}"
sizes="(max-width: {$image_by_size.width}px) 100vw, {$image_by_size.width}px"></a>
{if $caption}
<figcaption class="widget-image-caption ce-caption-text">{$caption}</figcaption></figure>
{/if}
</div></div></div><div class="elementor-element elementor-element-eb590ec elementor-align-center elementor-widget elementor-widget-product-miniature-add-to-cart elementor-widget-button" data-id="eb590ec" data-element_type="widget" data-widget_type="product-miniature-add-to-cart.default"><div class="elementor-widget-container">{if $product.available_for_order && !$configuration.is_catalog}
<div class="elementor-button-wrapper"><a class="{if $product.attributes and $product.quantity_all_versions}elementor-button-combinations{/if} elementor-button elementor-size-sm elementor-animation-push" {if $product.attributes && $product.quantity_all_versions}href="#ce-action=quickview"{elseif $product.add_to_cart_url}href="#ce-action=addToCart{if $product.minimal_quantity > 1}&amp;qty={$product.minimal_quantity}{/if}"{/if} role="button"><span class="elementor-button-content-wrapper"><span class="elementor-button-icon elementor-align-icon-left"><i class="{if $product.attributes}ceicon ceicon-magnifier{else}ceicon-basket-solid{/if}" aria-hidden="true"></i></span><span class="elementor-button-text">{if $product.attributes && $product.quantity_all_versions}Quick View{else}Add to Cart{/if}</span></span></a></div>
{/if}</div></div><div class="elementor-element elementor-element-d9c527f elementor-widget elementor-widget-product-miniature-name elementor-widget-heading" data-id="d9c527f" data-element_type="widget" data-widget_type="product-miniature-name.default"><div class="elementor-widget-container"><p class="ce-product-name elementor-heading-title"><a href="{$product.url}">{$product.name}</a></p></div></div><section class="elementor-element elementor-element-6c6a146 elementor-section-boxed elementor-section-height-default elementor-section-height-default elementor-section elementor-inner-section" data-id="6c6a146" data-element_type="section"><div class="elementor-container elementor-column-gap-default"><div class="elementor-row"><div class="elementor-element elementor-element-6ce320a ce-valign-center elementor-column elementor-col-50 elementor-inner-column" data-id="6ce320a" data-element_type="column"><div class="elementor-column-wrap elementor-element-populated"><div class="elementor-widget-wrap"><div class="elementor-element elementor-element-94cc222 elementor-widget__width-initial ce-product-prices--layout-stacked elementor-widget elementor-widget-product-miniature-price elementor-overflow-hidden elementor-widget-product-price" data-id="94cc222" data-element_type="widget" data-widget_type="product-miniature-price.default"><div class="elementor-widget-container">
{if $product.show_price}
<div class="ce-product-prices">
{if $product.has_discount}
{hook h='displayProductPriceBlock' product=$product type='old_price'}
<div class="ce-product-price-regular">{$product.regular_price}</div>
{/if}
{hook h='displayProductPriceBlock' product=$product type='before_price'}
{capture assign='ce_price'}{hook h='displayProductPriceBlock' product=$product type='custom_price' hook_origin='products_list'}{/capture}
<div class="ce-product-price{if $product.has_discount} ce-has-discount{/if}"><span>{if $ce_price}{$ce_price nofilter}{else}{$product.price}{/if}</span>
{if $product.has_discount}
{if 'percentage' === $product['discount_type']}
<span class="ce-product-badge ce-product-badge-sale ce-product-badge-sale-percentage">
{l s='Save %percentage%' sprintf=['%percentage%' => $product.discount_percentage_absolute] d='Shop.Theme.Catalog'}
</span>
{else}
<span class="ce-product-badge ce-product-badge-sale ce-product-badge-sale-amount">
{l s='Save %amount%' sprintf=['%amount%' => $product.discount_to_display] d='Shop.Theme.Catalog'}
</span>
{/if}
{/if}
</div>
{hook h='displayProductPriceBlock' product=$product type='weight'}
</div>
{/if}
</div></div></div></div></div><div class="elementor-element elementor-element-b11e9dd ce-valign-center elementor-column elementor-col-50 elementor-inner-column" data-id="b11e9dd" data-element_type="column"><div class="elementor-column-wrap elementor-element-populated"><div class="elementor-widget-wrap"><div class="elementor-element elementor-element-102b66a elementor-align-right elementor-widget__width-initial elementor-widget elementor-widget-product-miniature-add-to-cart elementor-widget-button" data-id="102b66a" data-element_type="widget" data-widget_type="product-miniature-add-to-cart.default"><div class="elementor-widget-container">{if $product.available_for_order && !$configuration.is_catalog}
<div class="elementor-button-wrapper"><a {if $product.add_to_cart_url}href="#ce-action=addToCart{if $product.minimal_quantity > 1}&amp;qty={$product.minimal_quantity}{/if}"{/if} class="elementor-button elementor-size-sm" role="button"><span class="elementor-button-content-wrapper"><span class="elementor-button-icon elementor-align-icon-left"><i class="ceicon-basket-solid" aria-hidden="true"></i></span><span class="elementor-button-text">Buy</span></span></a></div>
{/if}</div></div></div></div></div></div></div></section></div></div></div></div></div></div></article></div>