
services:
  prestashop:
    container_name: prestashop
    image: darthshop/darth-shop:latest
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 1G
    restart: unless-stopped
    depends_on:
      - memcached-server
    ports:
      - 19668:443
    volumes:
      - ./prestashop:/var/www/html
      - ./ssl:/etc/apache2/ssl:ro
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=admin-mysql_db
      - DB_USER=root
      - DB_PASSWD=student
      - DB_NAME=BE_196687
      - PS_INSTALL_AUTO=1
      - PS_FOLDER_ADMIN=admin087pqsbei
      - MEMCACHED_HOST=memcached-server
      - MEMCACHED_PORT=11211
    networks:
      - prestashop
      - admin-mysql_default

  memcached-server:
    container_name: memcached-server
    image: memcached
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 1G
    networks:
      - prestashop

networks:
  prestashop:
  admin-mysql_default:
    external: true
