<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJlmmiwk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJlmmiwk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJlmmiwk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJlmmiwk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJlmmiwk\appDevDebugProjectContainer([
    'container.build_hash' => 'Jlmmiwk',
    'container.build_id' => '01be8f7c',
    'container.build_time' => 1732305084,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJlmmiwk');
