<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxk6nou\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxk6nou/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGxk6nou.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGxk6nou\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGxk6nou\appDevDebugProjectContainer([
    'container.build_hash' => 'Gxk6nou',
    'container.build_id' => 'eda4be19',
    'container.build_time' => 1733883708,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxk6nou');
