<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWgygvxs\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWgygvxs/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWgygvxs.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWgygvxs\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWgygvxs\appDevDebugProjectContainer([
    'container.build_hash' => 'Wgygvxs',
    'container.build_id' => '5459546c',
    'container.build_time' => 1733842557,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWgygvxs');
